export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const FETCH_COURSES = "FETCH_COURSES";
export const LOAD_STUDENTS_FOR_COURSE = "LOAD_STUDENTS_FOR_COURSE";
export const FETCH_STUDENT_DETAILS = "FETCH_STUDENT_DETAILS";
